/** Sieve script generation and parsing for filter rules */

import type { FilterRule, FilterCondition, FilterAction } from "@/types/filter-rules.ts";

/** Determine which Sieve extensions a set of rules requires */
function getRequiredExtensions(rules: FilterRule[]): string[] {
  const extensions = new Set<string>();

  for (const rule of rules) {
    for (const condition of rule.conditions) {
      if (condition.field === "body") {
        extensions.add("body");
      }
      if (condition.operator === "regex") {
        extensions.add("regex");
      }
    }
    for (const action of rule.actions) {
      switch (action.type) {
        case "moveTo":
          extensions.add("fileinto");
          break;
        case "copyTo":
          extensions.add("fileinto");
          extensions.add("copy");
          break;
        case "star":
        case "markRead":
          extensions.add("imap4flags");
          break;
        case "forward":
          extensions.add("redirect");
          break;
        case "reject":
          extensions.add("reject");
          break;
      }
    }
  }

  return Array.from(extensions).sort();
}

/** Generate a Sieve condition test from a FilterCondition */
function generateConditionTest(condition: FilterCondition): string {
  const { field, operator, value } = condition;

  // Size comparisons
  if (field === "size") {
    if (operator === "greaterThan") {
      return `size :over ${value}`;
    }
    return `size :under ${value}`;
  }

  // hasAttachment (value is ignored, operator is ignored)
  if (field === "hasAttachment") {
    return `header :contains "Content-Type" "multipart/mixed"`;
  }

  // Header field mapping
  const headerMap: Record<string, string> = {
    from: "From",
    to: "To",
    cc: "Cc",
    subject: "Subject",
  };

  // Body test
  if (field === "body") {
    const matchType = operatorToSieveMatchType(operator);
    return `body :text ${matchType} ${sieveQuote(value)}`;
  }

  // Header tests
  const headerName = headerMap[field];
  if (headerName) {
    const matchType = operatorToSieveMatchType(operator);
    return `header ${matchType} ${sieveQuote(headerName)} ${sieveQuote(value)}`;
  }

  // Fallback
  return `header :contains "From" ${sieveQuote(value)}`;
}

/** Convert our operator to Sieve match type */
function operatorToSieveMatchType(operator: FilterCondition["operator"]): string {
  switch (operator) {
    case "contains":
      return ":contains";
    case "equals":
      return ":is";
    case "startsWith":
      return ":matches";
    case "endsWith":
      return ":matches";
    case "regex":
      return ":regex";
    default:
      return ":contains";
  }
}

/** Wrap a value in Sieve-safe quotes */
function sieveQuote(value: string): string {
  // Escape backslashes and quotes
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/** Adjust value for wildcard matching */
function adjustValueForMatch(
  operator: FilterCondition["operator"],
  value: string,
): string {
  if (operator === "startsWith") return `${value}*`;
  if (operator === "endsWith") return `*${value}`;
  return value;
}

/** Generate Sieve actions from FilterAction[] */
function generateActions(actions: FilterAction[]): string[] {
  const lines: string[] = [];

  for (const action of actions) {
    switch (action.type) {
      case "moveTo":
        lines.push(`  fileinto ${sieveQuote(action.value ?? "")};`);
        break;
      case "copyTo":
        lines.push(`  fileinto :copy ${sieveQuote(action.value ?? "")};`);
        break;
      case "markRead":
        lines.push(`  addflag "\\\\Seen";`);
        break;
      case "star":
        lines.push(`  addflag "\\\\Flagged";`);
        break;
      case "forward":
        lines.push(`  redirect ${sieveQuote(action.value ?? "")};`);
        break;
      case "delete":
        lines.push(`  discard;`);
        break;
      case "reject":
        lines.push(`  reject ${sieveQuote(action.value ?? "Message rejected")};`);
        break;
    }
  }

  return lines;
}

/**
 * Convert a list of FilterRule[] into a Sieve script.
 * Includes rule metadata in comments for round-trip parsing.
 */
export function generateSieveScript(rules: FilterRule[]): string {
  if (rules.length === 0) {
    return '# Webmail filter rules\n# No rules defined\nrequire ["fileinto"];\n';
  }

  const sortedRules = [...rules].sort((a, b) => a.order - b.order);
  const extensions = getRequiredExtensions(sortedRules);
  if (extensions.length === 0) {
    extensions.push("fileinto");
  }

  const lines: string[] = [];
  lines.push("# Webmail filter rules");
  lines.push("# Auto-generated by webmail. Do not edit manually.");
  lines.push("");
  lines.push(`require [${extensions.map((e) => `"${e}"`).join(", ")}];`);
  lines.push("");

  for (const rule of sortedRules) {
    // Metadata comment
    lines.push(`# Rule: ${rule.name} (id: ${rule.id}, enabled: ${rule.enabled})`);
    lines.push(`# META: ${JSON.stringify({ id: rule.id, name: rule.name, enabled: rule.enabled, order: rule.order, conditionMatch: rule.conditionMatch })}`);

    if (!rule.enabled) {
      // Write disabled rule as comments
      const ruleLines = generateRuleBlock(rule);
      for (const line of ruleLines) {
        lines.push(`# ${line}`);
      }
      lines.push("");
      continue;
    }

    const ruleLines = generateRuleBlock(rule);
    lines.push(...ruleLines);
    lines.push("");
  }

  return lines.join("\n");
}

/** Generate the if-block for a single rule */
function generateRuleBlock(rule: FilterRule): string[] {
  const lines: string[] = [];
  const matchType = rule.conditionMatch === "all" ? "allof" : "anyof";

  // Generate conditions
  const conditions = rule.conditions.map((c) => {
    const adjusted = { ...c };
    if (c.operator === "startsWith" || c.operator === "endsWith") {
      adjusted.value = adjustValueForMatch(c.operator, c.value);
    }
    return generateConditionTest(adjusted);
  });

  if (conditions.length === 1) {
    lines.push(`if ${conditions[0]} {`);
  } else {
    lines.push(`if ${matchType} (`);
    for (let i = 0; i < conditions.length; i++) {
      const comma = i < conditions.length - 1 ? "," : "";
      lines.push(`  ${conditions[i]}${comma}`);
    }
    lines.push(`) {`);
  }

  // Generate actions
  const actionLines = generateActions(rule.actions);
  lines.push(...actionLines);

  // Add stop to prevent further processing
  lines.push("  stop;");
  lines.push("}");

  return lines;
}

/**
 * Parse a Sieve script back into FilterRule[].
 * Uses the META comments for round-trip fidelity.
 */
export function parseSieveScript(script: string): FilterRule[] {
  const rules: FilterRule[] = [];
  const lines = script.split("\n");

  let i = 0;
  while (i < lines.length) {
    const line = lines[i];

    // Look for META comments
    const metaMatch = line.match(/^#\s*META:\s*(.+)$/);
    if (metaMatch) {
      try {
        const meta = JSON.parse(metaMatch[1]) as {
          id: string;
          name: string;
          enabled: boolean;
          order: number;
          conditionMatch: "all" | "any";
        };

        // Now parse the rule block (enabled or disabled)
        i++;
        const conditions: FilterCondition[] = [];
        const actions: FilterAction[] = [];

        // Skip forward to find the if block (may be commented out)
        const blockLines: string[] = [];
        const isDisabled = !meta.enabled;

        // Collect lines until we hit an empty line or next META
        while (i < lines.length) {
          const currentLine = lines[i];

          // Stop at empty line or next rule
          if (currentLine.trim() === "" || (currentLine.startsWith("# Rule:") && i > 0)) {
            break;
          }

          if (isDisabled && currentLine.startsWith("# ")) {
            blockLines.push(currentLine.slice(2));
          } else if (!isDisabled) {
            blockLines.push(currentLine);
          }
          i++;
        }

        // Parse conditions and actions from block lines
        parseBlockLines(blockLines, conditions, actions);

        rules.push({
          id: meta.id,
          name: meta.name,
          enabled: meta.enabled,
          order: meta.order,
          conditions: conditions.length > 0
            ? conditions
            : [{ field: "from", operator: "contains", value: "" }],
          conditionMatch: meta.conditionMatch,
          actions: actions.length > 0
            ? actions
            : [{ type: "moveTo", value: "" }],
        });
      } catch {
        i++;
      }
      continue;
    }

    i++;
  }

  return rules;
}

/** Parse condition and action lines from a Sieve block */
function parseBlockLines(
  lines: string[],
  conditions: FilterCondition[],
  actions: FilterAction[],
): void {
  for (const line of lines) {
    const trimmed = line.trim();

    // Parse header conditions
    const headerMatch = trimmed.match(
      /header\s+(:contains|:is|:matches|:regex)\s+"(\w+)"\s+"([^"]*)"/,
    );
    if (headerMatch) {
      const [, matchType, headerName, value] = headerMatch;
      const fieldMap: Record<string, FilterCondition["field"]> = {
        From: "from",
        To: "to",
        Cc: "cc",
        Subject: "subject",
      };
      const field = fieldMap[headerName] ?? "from";
      const operator = sieveMatchTypeToOperator(matchType, value);
      const cleanValue = cleanMatchValue(operator, value);
      conditions.push({ field, operator, value: cleanValue });
      continue;
    }

    // Parse body conditions
    const bodyMatch = trimmed.match(
      /body\s+:text\s+(:contains|:is|:matches|:regex)\s+"([^"]*)"/,
    );
    if (bodyMatch) {
      const [, matchType, value] = bodyMatch;
      const operator = sieveMatchTypeToOperator(matchType, value);
      const cleanValue = cleanMatchValue(operator, value);
      conditions.push({ field: "body", operator, value: cleanValue });
      continue;
    }

    // Parse size conditions
    const sizeMatch = trimmed.match(/size\s+:(over|under)\s+(\S+)/);
    if (sizeMatch) {
      const [, dir, value] = sizeMatch;
      conditions.push({
        field: "size",
        operator: dir === "over" ? "greaterThan" : "lessThan",
        value,
      });
      continue;
    }

    // Parse actions
    const fileintoMatch = trimmed.match(/fileinto\s+(?::copy\s+)?"([^"]*)"/);
    if (fileintoMatch) {
      const isCopy = trimmed.includes(":copy");
      actions.push({
        type: isCopy ? "copyTo" : "moveTo",
        value: fileintoMatch[1],
      });
      continue;
    }

    if (trimmed.match(/addflag\s+"\\\\Seen"/)) {
      actions.push({ type: "markRead" });
      continue;
    }

    if (trimmed.match(/addflag\s+"\\\\Flagged"/)) {
      actions.push({ type: "star" });
      continue;
    }

    const redirectMatch = trimmed.match(/redirect\s+"([^"]*)"/);
    if (redirectMatch) {
      actions.push({ type: "forward", value: redirectMatch[1] });
      continue;
    }

    if (trimmed === "discard;") {
      actions.push({ type: "delete" });
      continue;
    }

    const rejectMatch = trimmed.match(/reject\s+"([^"]*)"/);
    if (rejectMatch) {
      actions.push({ type: "reject", value: rejectMatch[1] });
      continue;
    }
  }
}

/** Convert Sieve match type back to our operator */
function sieveMatchTypeToOperator(
  matchType: string,
  value: string,
): FilterCondition["operator"] {
  switch (matchType) {
    case ":contains":
      return "contains";
    case ":is":
      return "equals";
    case ":matches":
      if (value.startsWith("*")) return "endsWith";
      if (value.endsWith("*")) return "startsWith";
      return "contains";
    case ":regex":
      return "regex";
    default:
      return "contains";
  }
}

/** Remove wildcard characters from match values */
function cleanMatchValue(operator: FilterCondition["operator"], value: string): string {
  if (operator === "startsWith" && value.endsWith("*")) {
    return value.slice(0, -1);
  }
  if (operator === "endsWith" && value.startsWith("*")) {
    return value.slice(1);
  }
  return value;
}
